#!/usr/bin/env bash
#
# build-stack.sh - assemble a headless developer-desktop image from components.
# ---------------------------------------------------------------------------
# An "admin type" composes a stack by listing components in stacks/<name>.stack;
# this builder resolves their dependencies, orders them, generates a Dockerfile,
# and (optionally) builds the image. Each component lives in its own directory
# under components/<category>/<name>/ so technologies stay decoupled and reusable.
#
#   ./build-stack.sh --list                 # list stacks and components
#   ./build-stack.sh --print java-enterprise # show the generated Dockerfile
#   ./build-stack.sh --no-build java-enterprise
#   ./build-stack.sh java-enterprise         # generate + docker build
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMPONENTS_ROOT="${REPO_ROOT}/components"
STACKS_ROOT="${REPO_ROOT}/stacks"
BUILD_ROOT="${REPO_ROOT}/build"

# Stamp the build (Eastern, DST-aware) without relying on Date.now in tooling.
BUILD_TS="$(TZ=America/New_York date '+%Y-%m-%d %H:%M') ET"
TAG_TS="$(TZ=America/New_York date '+%Y-%m-%d')"

DO_BUILD=1
PRINT_ONLY=0
TAG=""

usage() {
  sed -n '2,18p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
  exit "${1:-0}"
}

die()  { echo "ERROR: $*" >&2; exit 1; }
info() { echo ">> $*"; }

# --- discovery -------------------------------------------------------------
list_all() {
  echo "Available stacks (stacks/*.stack):"
  local f
  for f in "${STACKS_ROOT}"/*.stack; do
    [[ -e "$f" ]] || { echo "  (none)"; break; }
    local name desc
    name="$(basename "$f" .stack)"
    desc="$(. "$f"; echo "${DESCRIPTION:-}")"
    printf "  %-22s %s\n" "${name}" "${desc}"
  done
  echo
  echo "Available components (components/<category>/<name>):"
  local meta
  while IFS= read -r meta; do
    local id cat desc
    id="${meta#"${COMPONENTS_ROOT}/"}"; id="${id%/meta}"
    desc="$(. "$meta"; echo "${DESCRIPTION:-}")"
    printf "  %-26s %s\n" "${id}" "${desc}"
  done < <(find "${COMPONENTS_ROOT}" -name meta | sort)
}

# --- dependency resolution -------------------------------------------------
# Recursively expand a component's REQUIRES, emitting dependencies before the
# component itself. A visiting-set guards against cycles.
declare -A _VISITED=()
declare -A _ON_STACK=()
ORDERED=()

component_requires() {
  local id="$1" meta="${COMPONENTS_ROOT}/$1/meta"
  [[ -f "${meta}" ]] || die "component '${id}' not found (expected ${meta})"
  ( . "${meta}"; echo "${REQUIRES:-}" )
}

resolve() {
  local id="$1" dep
  [[ -n "${_VISITED[$id]:-}" ]] && return 0
  [[ -n "${_ON_STACK[$id]:-}" ]] && die "dependency cycle detected at component '${id}'"
  _ON_STACK[$id]=1
  for dep in $(component_requires "${id}"); do
    resolve "${dep}"
  done
  unset '_ON_STACK[$id]'
  _VISITED[$id]=1
  ORDERED+=("${id}")
}

# --- Dockerfile generation -------------------------------------------------
generate_dockerfile() {
  local base="$1"; shift
  local stack_name="$1"; shift
  local description="$1"; shift
  local components=("$@")

  cat <<EOF
# syntax=docker/dockerfile:1
# ===========================================================================
#  AUTO-GENERATED by build-stack.sh - DO NOT EDIT BY HAND.
#  Stack:       ${stack_name}
#  Description: ${description}
#  Components:  ${components[*]}
#  Built:       ${BUILD_TS}
# ===========================================================================
FROM ${base}

LABEL maintainer="Acknowledged Development Inc. help@ackdev.com" \\
      org.opencontainers.image.title="devstack-${stack_name}" \\
      org.opencontainers.image.description="${description}" \\
      io.openshift.expose-services="6901:http,5901:xvnc"

ENV DEBIAN_FRONTEND=noninteractive \\
    STACKBUILD=/stackbuild \\
    COMPONENTS_DIR=/stackbuild/components \\
    STACK_NAME=${stack_name} \\
    STACK_BUILD_TIMESTAMP="${BUILD_TS}" \\
    HOME=/home/superstar \\
    CONTAINER_USER=superstar \\
    DISPLAY=:1 \\
    VNC_PORT=5901 \\
    NO_VNC_PORT=6901 \\
    VNC_COL_DEPTH=24 \\
    VNC_RESOLUTION=1280x1024 \\
    NO_VNC_HOME=/headless/noVNC \\
    LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8

EXPOSE \$VNC_PORT \$NO_VNC_PORT

# Shared build-time helpers + runtime scripts
COPY stackbuild /stackbuild
RUN find /stackbuild -name '*.sh' -exec chmod a+x {} +
EOF

  local id
  for id in "${components[@]}"; do
    cat <<EOF

# --- component: ${id} ---
COPY components/${id} /stackbuild/components/${id}
RUN /stackbuild/run-component.sh ${id}
EOF
  done

  cat <<EOF

# Finalize: clean apt caches, tidy build artifacts
RUN /stackbuild/finalize.sh

ENTRYPOINT ["/stackbuild/entrypoint.sh"]
CMD ["--wait"]
EOF
}

# --- main ------------------------------------------------------------------
[[ $# -gt 0 ]] || usage 1

POSITIONAL=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help) usage 0 ;;
    --list)    list_all; exit 0 ;;
    --print)   PRINT_ONLY=1; DO_BUILD=0; shift ;;
    --no-build) DO_BUILD=0; shift ;;
    --tag)     TAG="${2:?--tag needs a value}"; shift 2 ;;
    -*)        die "unknown option: $1" ;;
    *)         POSITIONAL+=("$1"); shift ;;
  esac
done

[[ ${#POSITIONAL[@]} -eq 1 ]] || usage 1
STACK_ARG="${POSITIONAL[0]}"

# Resolve the stack file (accept a name or a path)
if [[ -f "${STACK_ARG}" ]]; then
  STACK_FILE="${STACK_ARG}"
elif [[ -f "${STACKS_ROOT}/${STACK_ARG}.stack" ]]; then
  STACK_FILE="${STACKS_ROOT}/${STACK_ARG}.stack"
else
  die "stack '${STACK_ARG}' not found (looked for ${STACKS_ROOT}/${STACK_ARG}.stack)"
fi

# Load the stack definition
STACK_NAME=""; DESCRIPTION=""; BASE=""; COMPONENTS=""
# shellcheck source=/dev/null
source "${STACK_FILE}"
STACK_NAME="${STACK_NAME:-$(basename "${STACK_FILE}" .stack)}"
BASE="${BASE:-ubuntu:22.04}"
[[ -n "${COMPONENTS}" ]] || die "stack '${STACK_NAME}' lists no COMPONENTS"

# Resolve dependency order
for c in ${COMPONENTS}; do
  resolve "${c}"
done

info "Stack:      ${STACK_NAME}"
info "Base image: ${BASE}"
info "Components (resolved order): ${ORDERED[*]}"

if [[ ${PRINT_ONLY} -eq 1 ]]; then
  generate_dockerfile "${BASE}" "${STACK_NAME}" "${DESCRIPTION}" "${ORDERED[@]}"
  exit 0
fi

# Write the generated Dockerfile into build/<stack>/
OUT_DIR="${BUILD_ROOT}/${STACK_NAME}"
mkdir -p "${OUT_DIR}"
DOCKERFILE="${OUT_DIR}/Dockerfile"
generate_dockerfile "${BASE}" "${STACK_NAME}" "${DESCRIPTION}" "${ORDERED[@]}" > "${DOCKERFILE}"
info "Generated ${DOCKERFILE}"

if [[ ${DO_BUILD} -eq 0 ]]; then
  info "--no-build set; skipping docker build."
  exit 0
fi

TAG="${TAG:-ackdev/devstack-${STACK_NAME}:${TAG_TS}}"
info "Building image ${TAG} (context: ${REPO_ROOT})"
docker build -f "${DOCKERFILE}" -t "${TAG}" "${REPO_ROOT}"
info "Built ${TAG}"
